### ISSUE TITLE
 Your package not working in apple m1 chip.

### ISSUE THREAD

**Issue by Balamurugan-JM** [xiqi/react-native-live-audio-stream#19]
When i install your package in mac m1 chip means the project is not ran in simulator. if i removed the package from the package.json the project will run in simulator .

<img width="504" alt="Screenshot 2022-11-04 at 2 07 29 PM" src="https://user-images.githubusercontent.com/87409226/199929225-d2e016cf-269a-4afb-8de1-161fae935453.png">

Thanks in advance

**Comment by LunatiqueCoder** [comment]
I have an Apple M1 chip and it works fine. The problem sure is only on your side.

EDIT: @Balamurugan-JM you probably have to run `cd ios && pod install && cd ..` in your terminal after running `yarn add`

**Comment by Romick2005** [comment]
Confirmed. Works fine for me on MacMini M1 2020.
@Balamurugan-JM this should be closed.
