### ISSUE TITLE
Can the LiveAudioStream.init(options) take bufferSize as an input?

### ISSUE THREAD

**Issue by sbsujith** [xiqi/react-native-live-audio-stream#3]
Can the LiveAudioStream.init(options) take bufferSize as an input?
Currently the buffer size i get after conversion by Buffer.from(data, 'base64') is 2048. I would like to get a size of 4096.

Is that possible?
Thank you in advance

**Comment by xiqi** [comment]
@thomasbrueggemann  Thanks for the PR!
And my apologies for forgetting about this issue for a long time!
