### ISSUE TITLE
[Question] Can we get full file when we stop the recorder ?

### ISSUE THREAD

**Issue by umang-simform** [xiqi/react-native-live-audio-stream#7]
We need a similar library that can provide us buffer data to accomplish with the live transcription feature but the thing is we need to save and send the audio when the user stops the recorder. As I can see the main library has this feature so if you can provide this information then it would be really helpful.

**Comment by dorthwein** [comment]
Use the original package this was inspired by.  See documents, long story short that package does the file write when done recording and allows for you to tap into the data stream.

**Comment by umang-simform** [comment]
Yeah already checked that, thanks
